export default {
  "login": "MohamedElsayed002",
  "id": 99518714,
  "node_id": "U_kgDOBe6I-g",
  "avatar_url": "https://avatars.githubusercontent.com/u/99518714?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MohamedElsayed002",
  "html_url": "https://github.com/MohamedElsayed002",
  "followers_url": "https://api.github.com/users/MohamedElsayed002/followers",
  "following_url": "https://api.github.com/users/MohamedElsayed002/following{/other_user}",
  "gists_url": "https://api.github.com/users/MohamedElsayed002/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MohamedElsayed002/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MohamedElsayed002/subscriptions",
  "organizations_url": "https://api.github.com/users/MohamedElsayed002/orgs",
  "repos_url": "https://api.github.com/users/MohamedElsayed002/repos",
  "events_url": "https://api.github.com/users/MohamedElsayed002/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MohamedElsayed002/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mohamed Elsayed Ali",
  "company": null,
  "blog": "",
  "location": "Alexandria",
  "email": null,
  "hireable": null,
  "bio": "Hi, My name is Mohamed. I'm 20years old. Student at the Faculty of the Science University of Alexandria and my major is CS. I'd love to share my coding journey",
  "twitter_username": "Mohamed23529203",
  "public_repos": 36,
  "public_gists": 0,
  "followers": 0,
  "following": 3,
  "created_at": "2022-02-12T01:49:32Z",
  "updated_at": "2023-04-18T20:25:39Z"
}